// apps/angular-app/src/app/pokemon-detail/pokemon-detail.ts
import { Component, signal } from "@angular/core";
import { type ActivatedRoute, RouterLink } from "@angular/router";
import { createGunsoleClient } from "@gunsole/web";

const gunsole = createGunsoleClient({
  projectId: "test-project-angular",
  apiKey: "test-api-key",
  mode: "local",
  env: "development",
  appName: "Angular App",
  appVersion: "1.0.0",
  defaultTags: { framework: "angular" },
});

interface Pokemon {
  id: number;
  name: string;
  height: number;
  weight: number;
  base_experience: number;
  sprites: {
    front_default: string;
    front_shiny: string;
  };
  types: Array<{ type: { name: string } }>;
  abilities: Array<{ ability: { name: string }; is_hidden: boolean }>;
  stats: Array<{ base_stat: number; stat: { name: string } }>;
}

@Component({
  selector: "app-pokemon-detail",
  imports: [RouterLink],
  templateUrl: "./pokemon-detail.html",
  styleUrl: "./pokemon-detail.css",
})
export class PokemonDetail {
  protected readonly pokemon = signal<Pokemon | null>(null);
  protected readonly loading = signal(true);
  protected readonly error = signal<string | null>(null);

  constructor(private route: ActivatedRoute) {
    const id = this.route.snapshot.paramMap.get("id");
    if (id) this.fetchPokemon(id);
  }

  private async fetchPokemon(id: string): Promise<void> {
    const traceId = `trace-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
    const startTime = performance.now();

    this.loading.set(true);
    this.error.set(null);

    gunsole.info({
      message: `Fetching Pokemon detail: ${id}`,
      bucket: "api_request",
      context: { pokemonId: id },
      tags: { api: "pokeapi", action: "detail_fetch_start" },
      traceId,
    });

    try {
      const response = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`);
      if (!response.ok) throw new Error(`Pokemon not found: ${id}`);

      const data: Pokemon = await response.json();
      const totalTime = performance.now() - startTime;
      this.pokemon.set(data);

      gunsole.info({
        message: `Pokemon detail fetched: ${data.name}`,
        bucket: "api_request",
        context: {
          pokemon: data.name,
          pokemonId: data.id,
          totalTimeMs: Math.round(totalTime),
        },
        tags: { api: "pokeapi", action: "detail_fetch_success" },
        traceId,
      });
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : "Unknown error";
      this.error.set(errorMessage);

      gunsole.error({
        message: `Failed to fetch Pokemon detail: ${id}`,
        bucket: "api_request",
        context: { pokemonId: id, error: errorMessage },
        tags: { api: "pokeapi", action: "detail_fetch_error" },
        traceId,
      });
    } finally {
      this.loading.set(false);
    }
  }

  protected getStatWidth(baseStat: number): string {
    return `${Math.min(100, (baseStat / 255) * 100)}%`;
  }

  protected getAbilitiesText(abilities: Pokemon["abilities"]): string {
    return abilities
      .map((a) => a.ability.name + (a.is_hidden ? " (hidden)" : ""))
      .join(", ");
  }
}

// apps/react-vite/src/PokemonDetail.tsx
import { Link, useParams } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { gunsole } from "./gunsole";

interface Pokemon {
  id: number;
  name: string;
  height: number;
  weight: number;
  base_experience: number;
  sprites: {
    front_default: string;
    front_shiny: string;
  };
  types: Array<{ type: { name: string } }>;
  abilities: Array<{ ability: { name: string }; is_hidden: boolean }>;
  stats: Array<{ base_stat: number; stat: { name: string } }>;
}

export default function PokemonDetail() {
  const { pokemonId } = useParams({ from: "/pokemon/$pokemonId" });
  const [pokemon, setPokemon] = useState<Pokemon | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchPokemon = useCallback(async () => {
    const traceId = `trace-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
    const startTime = performance.now();

    setLoading(true);
    setError(null);

    gunsole.info({
      message: `Fetching Pokemon detail: ${pokemonId}`,
      bucket: "api_request",
      context: { pokemonId },
      tags: { api: "pokeapi", action: "detail_fetch_start" },
      traceId,
    });

    try {
      const response = await fetch(
        `https://pokeapi.co/api/v2/pokemon/${pokemonId}`
      );
      if (!response.ok) throw new Error(`Pokemon not found: ${pokemonId}`);

      const data: Pokemon = await response.json();
      const totalTime = performance.now() - startTime;
      setPokemon(data);

      gunsole.info({
        message: `Pokemon detail fetched: ${data.name}`,
        bucket: "api_request",
        context: { pokemon: data.name, pokemonId: data.id, totalTimeMs: Math.round(totalTime) },
        tags: { api: "pokeapi", action: "detail_fetch_success" },
        traceId,
      });
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : "Unknown error";
      setError(errorMessage);

      gunsole.error({
        message: `Failed to fetch Pokemon detail: ${pokemonId}`,
        bucket: "api_request",
        context: { pokemonId, error: errorMessage },
        tags: { api: "pokeapi", action: "detail_fetch_error" },
        traceId,
      });
    } finally {
      setLoading(false);
    }
  }, [pokemonId]);

  useEffect(() => {
    fetchPokemon();
  }, [fetchPokemon]);

  return (
    <div className="min-h-screen bg-zinc-900 text-white p-8">
      <div className="max-w-2xl mx-auto">
        <Link
          to="/"
          className="text-indigo-400 hover:text-indigo-300 mb-6 inline-block"
        >
          &larr; Back
        </Link>

        {loading && <p className="text-zinc-400">Loading...</p>}
        {error && <p className="text-red-400">{error}</p>}

        {pokemon && (
          <div className="bg-zinc-800 rounded-xl p-8">
            <div className="flex justify-center gap-6 mb-6">
              <div className="text-center">
                <img
                  src={pokemon.sprites.front_default}
                  alt="Default"
                  className="w-32 h-32 [image-rendering:pixelated]"
                />
                <span className="text-xs text-zinc-400">Default</span>
              </div>
              <div className="text-center">
                <img
                  src={pokemon.sprites.front_shiny}
                  alt="Shiny"
                  className="w-32 h-32 [image-rendering:pixelated]"
                />
                <span className="text-xs text-zinc-400">Shiny</span>
              </div>
            </div>

            <h1 className="text-3xl font-bold capitalize text-center mb-4">
              {pokemon.name}
            </h1>

            <div className="grid grid-cols-2 gap-4 text-zinc-300 mb-6">
              <p><span className="font-medium text-white">ID:</span> #{pokemon.id}</p>
              <p><span className="font-medium text-white">Base XP:</span> {pokemon.base_experience}</p>
              <p><span className="font-medium text-white">Height:</span> {pokemon.height / 10}m</p>
              <p><span className="font-medium text-white">Weight:</span> {pokemon.weight / 10}kg</p>
              <p><span className="font-medium text-white">Types:</span> {pokemon.types.map((t) => t.type.name).join(", ")}</p>
              <p><span className="font-medium text-white">Abilities:</span> {pokemon.abilities.map((a) => a.ability.name + (a.is_hidden ? " (hidden)" : "")).join(", ")}</p>
            </div>

            <div className="space-y-1">
              <span className="font-medium text-white text-sm">Stats:</span>
              {pokemon.stats.map((s) => (
                <div key={s.stat.name} className="flex items-center gap-2">
                  <span className="text-xs text-zinc-400 w-24 text-right capitalize">
                    {s.stat.name}
                  </span>
                  <div className="flex-1 bg-zinc-600 rounded-full h-2">
                    <div
                      className="bg-indigo-500 h-2 rounded-full"
                      style={{ width: `${Math.min(100, (s.base_stat / 255) * 100)}%` }}
                    />
                  </div>
                  <span className="text-xs text-zinc-300 w-8">{s.base_stat}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
